---
# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
# https://github.com/actions/stale
name: Mark stale issues and pull requests

permissions: read-all

on:
  schedule:
  - cron: '15 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-24.04
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions.
        stale-pr-message: |
          This PR has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'pinned'
        exempt-pr-labels: 'pinned'
