---
name: Update Dependencies

on:
  push:
    branches: # TODO: drop
      - "*"
  schedule:
    - cron: '0 2 * * *' # Täglich um 02:00 Uhr
  workflow_dispatch: # Ermöglicht manuelles Starten

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Updatecli
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli
        run: updatecli pipeline diff --config .github/updatecli.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}

      - name: Run Updatecli
        run: updatecli pipeline apply --config .github/updatecli.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}